### ISSUE TITLE
Allow setting MessageChannelDepth

### ISSUE THREAD

**Issue by tomasol** [brocaar/lora-gateway-bridge#114]
### Is this a bug or a feature request?
Feature request
### What did you expect?
I would like to set paho's MessageChannelDepth via config file.
Currently I believe one can enquee up to 100 messages to be published when connection is down, based on [this](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L112).
Please allow changing this via the [setter](https://github.com/eclipse/paho.mqtt.golang/blob/master/options.go#L330).

**Comment by blocknonip** [comment]
I didn't realize this feature already existed and was going to request this. +1, please make this configurable in the gateway bridge configuration.

**Comment by brocaar** [comment]
I'm closing this issue as this doesn't behave as one would expect, see the above link.
