### ISSUE TITLE
Bridge is not publishing in application topic

### ISSUE THREAD

**Issue by d3rf** [brocaar/lora-gateway-bridge#121]
### Is this a bug or a feature request?
BUG
### What did you expect?
Bridge publish in application topic
### What happened?
Events status up are publishing with no erros, just seen below. But phyPayload is crypted and we dont know how decrypted
'''
{"phyPayload":"QAEA/wOAAAABTzUhn6mgd0J2oncpWoa5XQ8=","txInfo":{"frequency":903900000,"modulation":"LORA","loRaModulationInfo":{"bandwidth":125,"spreadingFactor":7,"codeRate":"4/5","polarizationInversion":false}},"rxInfo":{"gatewayID":"uCfr//5Qoik=","time":null,"timeSinceGPSEpoch":null,"rssi":-65,"loRaSNR":10.8,"channel":0,"rfChain":0,"board":0,"antenna":0,"location":null,"fineTimestampType":"NONE","context":"HHMJuw=="}}
'''

Bridge has publised just once on application topic with decrypted data and no more publishing.
'''
{"applicationID":"1","applicationName":"Invision","deviceName":"No","devEUI":"0000000000000000","rxInfo":[{"gatewayID":"b827ebfffe50a229","name":"Campos","time":"2019-06-11T14:28:11.512039902Z","rssi":-63,"loRaSNR":8.8,"location":{"latitude":-21.752006316798564,"longitude":-41.22344724933007,"altitude":0}}],"txInfo":{"frequency":903900000,"dr":3},"adr":true,"fCnt":0,"fPort":1,"data":"SGVsbG8sIHdvcmxkIQ=="}
''''

**Comment by brocaar** [comment]
The LoRa Gateway Bridge does not publish to the application topic. This is the responsibility of the LoRa App Server and depends on the configured integrations. Please see https://www.loraserver.io/guides/troubleshooting/ for troubleshooting steps. As this might be related to encryption keys, I also suggest to search on https://forum.loraserver.io which contains a lot of questions / answers related encryption and / or MIC related issues.
