### ISSUE TITLE
section missing in .toml for mutlitech gateway

### ISSUE THREAD

**Issue by activiteOCR** [brocaar/lora-gateway-bridge#123]
### Is this a bug or a feature request?
In my opinion it's a bug for the .ipk and feature for preserving old configuration file
### What did you expect?
When updating lora-gateway-bridge from the gateway (multitech AEP in my case) get the same configuration file exposed here [https://www.loraserver.io/lora-gateway-bridge/install/config/]
### What happened?
When I download and install the latest lora-gateway-bridge .ipk package from: https://artifacts.loraserver.io/vendor/multitech/conduit/. the configuration file lora-gateway-bridge.toml is not complete, second point the command `lora-gateway-bridge configfile --config lora-gateway-bridge-old.toml > lora-gateway-bridge-new.toml`  doesn't work.
### What version are your using?
lora-gateway-bridge v3.0.1
loraserver V.3.0.1
lora-app-server V3.0.0
lora-geo-server V3.0.0
### How can your issue be reproduced?
When you download and install the latest .ipk from https://artifacts.loraserver.io/vendor/multitech/conduit/.
### Could you share your log output?
no really but the size of the lora-gateway-bridge is lower than the regular config file ( lot of section are missing), If really necessary I reinstall the lora-gateway-bridge V.3.0.1 on my multitech.

**Comment by brocaar** [comment]
This is not a bug, see this line: https://github.com/brocaar/lora-gateway-bridge/blob/master/packaging/vendor/multitech/conduit/files/lora-gateway-bridge.toml#L2.

```
lora-gateway-bridge configfile --config lora-gateway-bridge-old.toml > lora-gateway-bridge-new.toml
```

When you use the correct paths or when you execute it from the right directory, it does work :-)

```
/opt/lora-gateway-bridge/lora-gateway-bridge configfile --config /var/config/lora-gateway-bridge/lora-gateway-bridge.toml > /var/config/lora-gateway-bridge/lora-gateway-bridge-new.toml
```
