### ISSUE TITLE
Version of lora-gateway-bridge on Docker is not identical to v3.0.1

### ISSUE THREAD

**Issue by houluy** [brocaar/lora-gateway-bridge#127]
### Is this a bug or a feature request?
Bug
### What did you expect?
A LoRa-Gateway-Bridge of latest version by `docker pull loraserver/lora-gateway-bridge`
### What happened?
The version of LoRa-Gateway-Bridge on Docker is 39c91ac (maybe some commit) but not v3.0.1.
### What version are your using?
V3.0.1
### How can your issue be reproduced?
Install by `docker pull loraserver/lora-gateway-bridge`
### Could you share your log output?
```
sudo docker run --network="host" -v /home/user/loraserver:/mnt/loraserver loraserver/lora-gateway-bridge -c /mnt/loraserver/lora-gateway-bridge.toml version
39c91ac
```

**Comment by brocaar** [comment]
That is expected, `:latest` follows the `master` branch (see also https://www.loraserver.io/install/docker/). Pull:

* `loraserver/lora-gateway-bridge:3` for the latest `3.y.z` version -or-
* `loraserver/lora-gateway-bridge:3.0.1` to always pull v3.0.1
