### ISSUE TITLE
Microchip LoRa gateway 1.0.4 problem

### ISSUE THREAD

**Issue by KambaVVV** [brocaar/lora-gateway-bridge#131]
Hi Brocaar. I'm using the microchip LoRa gateway with the 1.0.4 version of the firmware installed. I've seen that in 2017 there were the same problem with the time parsing that I'm registering now. Does exist a solution to this problem? Thanks for you time and your kindness.

level=error msg="backend/semtechudp: could not handle packet" addr="GWIP" data_base64=AXwcAJJXY2VENxdFeyJzdGF0Ijp7InRpbWUiOiIyMDExLTAxLTAxVDA2OjAwOjM1WiIsInJ4bmIiOjIsInJ4b2siOjAsInJ4ZnciOjIsImFja3IiOjEwMCwiZHduYiI6MCwidHhuYiI6MH19 error="parsing time \"\"2011-01-01T06:00:35Z\"\" as \"\"2006-01-02 15:04:05 MST\"\": cannot parse \"T06:00:35Z\"\" as \" \""

**Comment by brocaar** [comment]
I have contacted Microchip a long time ago, but they did not solve this issue as far as I know. To keep the LoRa Gateway Bridge code clean and maintainable, I'm not planning to add a workaround for this issue as I believe this should be fixed in the gateway firmware.
