### ISSUE TITLE
lora-gateway-bridge exception

### ISSUE THREAD

**Issue by dragonfly1976** [brocaar/lora-gateway-bridge#136]
### Is this a bug or a feature request?
It's a bug
### What did you expect?
I expected to send "mosquitto_pub -t "gateway/7276ff000b030bcd/command/down -f /tmp/test.json" to it
### What happened?
The application crashed
### What version are your using?
SNAPSHOT-361697b
### How can your issue be reproduced?
The command "mosquitto_pub -t "gateway/7276ff000b030bcd/command/down -f /tmp/test.json" creates the same issue anytime i try. Json contains : {"confirmed" : false, "fport" : 2, "data" :"AQID"}
### Could you share your log output?
![LogAsPNG](https://user-images.githubusercontent.com/56167274/66221728-4e26c980-e6d8-11e9-85bf-701d03bb4c6b.png)

**Comment by brocaar** [comment]
This is an untagged version. I have looked into the line causing the exception (txInfo is nil), but I don't think this line is present in the latest tagged version.
