### ISSUE TITLE
mosquitto_sub -t "gateway/+/rx" time message was not set 

### ISSUE THREAD

**Issue by yuseunghyuk** [brocaar/lora-gateway-bridge#15]
lora_pkt_fwd : Version 3.0.0
log_lora-gateway-bridge : Version 2.1.0-3-gedf27bf

when I subscribe gateway's rx
time was not set like this.

"time":"0001-01-01T00:00:00Z"

log file is  below.

[log_lora-gateway-bridge-2.1.0-3-gedf27bf.txt](https://github.com/brocaar/lora-gateway-bridge/files/450955/log_lora-gateway-bridge-2.1.0-3-gedf27bf.txt)
[log_packet_forwarder-3.0.0.txt](https://github.com/brocaar/lora-gateway-bridge/files/450956/log_packet_forwarder-3.0.0.txt)
[log_mqtt_gateway_rx.txt](https://github.com/brocaar/lora-gateway-bridge/files/450957/log_mqtt_gateway_rx.txt)

**Comment by tftelkamp** [comment]
Does your gateway have a GPS? If not, lora_pkt_fwd will not send a time field. 

It would be better though if the lora-gateway-bridge would not include the time field either, instead of filling it with this default value.

**Comment by brocaar** [comment]
Thanks! I'll look into it after https://github.com/brocaar/loraserver/issues/68.
