### ISSUE TITLE
log errors on MQTT authentication

### ISSUE THREAD

**Issue by kruisdraad** [brocaar/lora-gateway-bridge#17]
when anonymous auth is disabled and you log in with wrong user/password the services stops / restart loops but does not log why. It should log something like 'MQTT login access denied for user xxxx'

**Comment by brocaar** [comment]
I've checked this locally, the output is:

```
INFO[0000] starting LoRa Gateway Bridge                  docs=https://docs.loraserver.io/lora-gateway-bridge/ version=2.1.2
INFO[0000] backend: connecting to mqtt broker            server=tcp://127.0.0.1:1883
FATA[0000] could not setup mqtt backend: Identifier rejected
```

Unfortunately, `Identifier rejected` is the only status that is returned by the mqtt library (and maybe by the broker?)
