### ISSUE TITLE
where to run packet forwarder 

### ISSUE THREAD

**Issue by a-farooq** [brocaar/lora-gateway-bridge#20]
Hi Brocaar,

I have done the setup given by you.
I m having Microchip gateway and motes. I m running the lora-gateway-bridge, loraserver, lora-app-server shared by you.

I m getting the packets from microchip gateway to the lora gateway bridge. 
But I m getting the following error.
=============
Error gateway: could not handle packet: parsing time 
=============

You said that running the three software only was required for the setup. Do I have to run packet forwarder too ?
If yes, where?

P.S. this question was already asked but it was closed and it did not solve my query.

**Comment by brocaar** [comment]
Could you tell me which `packet_forwarder` version you're using on your gateway?

**Comment by dhavalp** [comment]
Hi,
I have setup the lora server now I want to receive the data sent from MicroChip Lora Mote (RN2483) to the lora gateway bridge how to do that? If you can guide me. 

Thanks
