### ISSUE TITLE
Lorank8 status message support

### ISSUE THREAD

**Issue by jpmeijers** [brocaar/lora-gateway-bridge#26]
See:
https://github.com/TheThingsNetwork/ttn/issues/427

In short, the Lorank8 by default uses a different JSON format for its status messages. Example:
`{"time":"2017-01-19T18:02:38Z","dev":{"id":"1dee039aac75c307","lat":52.2388,"lon":6.8551,"alt":6,"up":93,"gps":"fake","pfrm":"Lorank","email":"j.vaningenschenau@utwente.nl","desc":"TTN Enschede macrocell gateway"},"prf":{"up_rf":0,"up_srv_dg":[0,1],"dw_srv_hb":[0.8333333333,1],"dw_srv_dg":[0,0],"dw_rf":[0.8333333333,1],"dw_bcn":0}}`

It will be great if this bridge can support the Lorank8 protocol too.

**Comment by brocaar** [comment]
I'm not really a big fan of supporting vendor-specific modifications of a  protocol (these things are really easy to add, but a pain to remove). Reading the original issue, I see that you would like to have support for the Lorank8 GPS info. These fields are already described in the "official" specs of the protocol, so wouldn't it be better to let the Lorank8 use these fields? https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT#L215
