### ISSUE TITLE
lora-gateway-bridge can't receive the packet from mote.

### ISSUE THREAD

**Issue by SoHyunYang** [brocaar/lora-gateway-bridge#29]
I run packet_forwarder and lora-gateway-bridge at the same time and let the LoRa mote send packet to the gateway.
(I used the iC880A as the gateway and the iM880B Starter kit as the mote.)
However, packet_fowrder confirmed that the packet was received, but the lora-gateway-bridge did not respond.

I thought of a problem. But I do not know if this caused this error. If it seems correct, please let me know about the values' ​​setting related server in global_conf.json file of packet forwarder.
![lora_gateway_bridge](https://cloud.githubusercontent.com/assets/17341294/23264812/09fa7bb8-fa26-11e6-840d-c00323cea019.png)
![packet_forwarder](https://cloud.githubusercontent.com/assets/17341294/23264819/0ee04450-fa26-11e6-80ee-fc34ad0ee899.png)

I was setting the global_conf.json file of pacekt_forwarder / lora_pkt_fwd. (Server_address: mqtt broker's tcp address, serv_port_up, serv_port_down: mqtt broker's port). But I think it is not right.

I wonder if there might be other problems.

Thank you.

**Comment by brocaar** [comment]
By default LoRa Gateway Bridge uses port 1700 for up and down. That might fix your issue.

**Comment by SoHyunYang** [comment]
ok. The defalut udp-bind value is port 1700. And I confirmed the port 1700's state is not "listen" or "established" when i am running lora-gateway-bridge. How can i do to solve this problem? 
![netstat](https://cloud.githubusercontent.com/assets/17341294/23329164/5bdbd698-fb75-11e6-8228-c15d7c9b95af.JPG)

The following information is the Installation Environment set by me.

lora app server, lora server, mqtt broker : in window
mqtt  tcp : 192.168. 0.11 , port :1883 
window ip : 192.168.0.11

lora-gateway, packet forwarder, lora-gateway-bridge : in raspberrypi connected with iC880A concentrator(gateway)
raspberrypi ip : 192.168.0.12

Thank you.
