### ISSUE TITLE
No /etc/lsb-release under Debian 

### ISSUE THREAD

**Issue by Champal** [brocaar/lora-gateway-bridge#30]
Hi, 

Here https://docs.loraserver.io/lora-gateway-bridge/getting-started/#setting-up-lora-gateway-bridge you 
use the file `/etc/lsb-release` that does not exist under Debian Jessie,  you have to use the `lsb_release` command instead.

```
source /etc/lsb-release
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1CE2AFD36DBCCA00
sudo echo "deb https://repos.loraserver.io/${DISTRIB_ID,,} ${DISTRIB_CODENAME} testing" | sudo tee /etc/apt/sources.list.d/loraserver.list
sudo apt-get update
```
You can replace `source /etc/lsb-release` by 
```
export DISTRIB_ID=`lsb_release -si`;export DISTRIB_CODENAME=`lsb_release -sc`
```

**Comment by brocaar** [comment]
Thanks @Champal, I'll fix this in the documentation.

**Comment by andykv59** [comment]
Will appreciate for the fix

**Comment by linas** [comment]
FWIW totally off-topic, but on my machine things were broken because `/etc/dpkg/origins/default -> /etc/dpkg/origins/ubuntu` instead of `/etc/dpkg/origins/default -> /etc/dpkg/origins/debian` like it should have been... and that broke lsb_release with cryptic python errors.

**Comment by hpsaturn** [comment]
> Hi,
> 
> Here https://docs.loraserver.io/lora-gateway-bridge/getting-started/#setting-up-lora-gateway-bridge you
> use the file `/etc/lsb-release` that does not exist under Debian Jessie, you have to use the `lsb_release` command instead.
> 
> ```
> source /etc/lsb-release
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1CE2AFD36DBCCA00
> sudo echo "deb https://repos.loraserver.io/${DISTRIB_ID,,} ${DISTRIB_CODENAME} testing" | sudo tee /etc/apt/sources.list.d/loraserver.list
> sudo apt-get update
> ```
> 
> You can replace `source /etc/lsb-release` by
> 
> ```
> export DISTRIB_ID=`lsb_release -si`;export DISTRIB_CODENAME=`lsb_release -sc`
> ```

Thanks. You can use in Debian:

```bash
source /etc/os-release
```
