### ISSUE TITLE
newTXPKFromTXPacket miss RFCh

### ISSUE THREAD

**Issue by hentaicreep** [brocaar/lora-gateway-bridge#36]
![1](https://user-images.githubusercontent.com/1901634/26884231-dc6c9a3e-4bd1-11e7-852f-5e05a9fed633.png)
TXPK defind RFCh but newTXPKFromTXPacket method don't use RFCh
![2](https://user-images.githubusercontent.com/1901634/26884364-313399aa-4bd2-11e7-9026-3ecc2631dc65.png)

**Comment by brocaar** [comment]
That is because the `RFCh` is not exposed through the `TXInfo` (https://github.com/brocaar/loraserver/blob/master/api/gw/gw.go#L55) struct. As far as I know this value must always be `0` as that is the only radio enabled for transmission. Do you have an usecase to set this to an other value?
