### ISSUE TITLE
Add option for logfile

### ISSUE THREAD

**Issue by minggi** [brocaar/lora-gateway-bridge#43]
With the LorixOne Gateway, I have problem to start the gateway as a deamon and to pipe the stout and sterr to a file. START-STOP-DEAMON has a problem with that. I think I have no other options...
The Gateway run with a yocto linux 2.1.2.

**Comment by brocaar** [comment]
What problem does `start-stop-daemon` have? Did you for example see this https://stackoverflow.com/questions/8251933/how-can-i-log-the-stdout-of-a-process-started-by-start-stop-daemon?

Also note that it might not be a good idea to persist logs on the gateway. I'm not sure about the LorixOne, but usually these devices do not have a lot of storage and the kind memory might not be suitable for lots of writes.
