### ISSUE TITLE
Log node frames not appearing

### ISSUE THREAD

**Issue by monkmahadeva** [brocaar/lora-gateway-bridge#49]
bug

I want to see the packets recieved in the frame_log

in loraserver config file LOG_NODE_FRAMES is set to true

loraserver version 0.20.0
![screenshot from 2017-08-16 14-33-19](https://user-images.githubusercontent.com/13939810/29355765-ea1f6a54-828f-11e7-86f8-22ab3517a2f4.png)

**Comment by brocaar** [comment]
1. Did you restart LoRa Server after changing the configuration?

You can see the current active environment variables using:

```bash
# get the PID of the loraserver process
ps aux |grep loraserver

# print process environment variables (replace {LORASERVER_PID_HERE} with the PID)
cat /proc/{LORASERVER_PID_HERE}/environ
```

2. Is the node activated? LoRa Server only logs frames for activated nodes. The fact that your gateway received a frame does not mean that the frame gets logged. It only gets logged for activated and authenticated nodes! E.g. when you receive data on the `application/+/node/+/rx` MQTT topic.

I don't think this is a bug, but if the above does not solve your issue, please open an issue here: https://github.com/brocaar/loraserver. As that is the component responsible for logging the frames.
