### ISSUE TITLE
otaa mode cannot connect

### ISSUE THREAD

**Issue by tornodo** [brocaar/lora-gateway-bridge#50]
pktfwd local_conf.json
 "serv_port_up": 1680,
 "serv_port_down": 1680
the node join success
+JOIN: Starting
+JOIN: NORMAL, count 1, 0s, 0s
+JOIN: Network joined
+JOIN: NetID 000000 DevAddr 01:65:14:01
+JOIN: Done

when changed
 "serv_port_up": 1700,
 "serv_port_down": 1700
restart pktfwd and start ./lora-gateway-bridge --mqtt-server tcp://x.x.x.x:1883
the node join failed
+JOIN: Starting
+JOIN: NORMAL, count 1, 0s, 0s
+JOIN: Join failed

**Comment by brocaar** [comment]
You need to install all LoRa Server components. Please see the documentation: https://docs.loraserver.io/install/quick-install/.
