### ISSUE TITLE
Why UDP??

### ISSUE THREAD

**Issue by monkmahadeva** [brocaar/lora-gateway-bridge#51]
Just one simple doubt. Why use of UDP for lora-gatewat-bridge.. Can we configure this with TCP/IP???

**Comment by brocaar** [comment]
That is exactly what the LoRa Gateway Bridge is for, converting the [packet_forwarder](https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT) UDP protocol into JSON over MQTT (thus TCP/IP).
