### ISSUE TITLE
Does the gateway bridge support the packet forwarder v2 v4.0.0

### ISSUE THREAD

**Issue by sabrine2020** [brocaar/lora-gateway-bridge#62]
### Is this a bug or a feature request?
Feature request

### What version are your using?
latest

### How can your issue be reproduced?
I am using kerlink IBTS, I installed the packet forwarder v2 v4.0.0 on it but seems like the gateway bridge is not supporting it, since I am getting 0 for RSSI and SNR values.

This issue is related to: [https://github.com/brocaar/lora-gateway-bridge/issues/44](url)
since the packet forwarder protocol is not the same.

Thanks,
Best reagrds

**Comment by brocaar** [comment]
I'm working on this and support should be available soon :-)

**Comment by brocaar** [comment]
I've merged the changes into `master`. Will be released shortly.
