### ISSUE TITLE
Lora-gateway-bridge for COAP protocol

### ISSUE THREAD

**Issue by ktsakos** [brocaar/lora-gateway-bridge#69]
Could i find a service in order to abstract the gateway's UDP packets to COAP/LWM2M protocol?

**Comment by brocaar** [comment]
That is not what the LoRa Gateway Bridge provides, but you could make your own service in between the MQTT broker and your COAP/LWM2M consumer?

**Comment by brocaar** [comment]
Currently I don't see a reason to add COAP support. I'm closing this issue.
