### ISSUE TITLE
Packets with no time

### ISSUE THREAD

**Issue by F-M-A** [brocaar/lora-gateway-bridge#72]
https://github.com/brocaar/lora-gateway-bridge/blob/5352d6f162767996253c21a940273d3f2593744c/gateway/backend.go#L446

Will it be posible to add system time to packets that does not have time var?

**Comment by brocaar** [comment]
Better not, as this would indicate the time when it was received by LoRa Gateway Bridge not when the frame was received . In case you would want to work around the GPS requirement to have this timestamp, it would be better to modify the packet-forwarder. This might be interesting too: https://forum.loraserver.io/t/http-integration-post-json-data-has-no-time-property/438
