### ISSUE TITLE
msg="gateway: could not handle packet: gateway: could not base64 decode data: illegal base64 data at input byte 0"

### ISSUE THREAD

**Issue by lf529** [brocaar/lora-gateway-bridge#79]
Using test data, the service returns the following information:
level=error msg="gateway: could not handle packet: gateway: could not base64 decode data: illegal base64 data at input byte 0"
Is there a problem with the test data?

Packet header:
Protocol version: 02
Random number: 35 52
Identification code: 00
Gateway MAC:0A 00 00 00 00 00 00 01

**Comment by brocaar** [comment]
Probably that is a yes ;-) Please see: https://docs.loraserver.io/lora-gateway-bridge/use/data/
