### ISSUE TITLE
Support for custom fields in The Things Network packet forwarder

### ISSUE THREAD

**Issue by htdvisser** [brocaar/lora-gateway-bridge#8]
The Things Network's version of the packet forwarder [adds a number of custom fields](https://github.com/TheThingsNetwork/packet_forwarder/commit/faa525b1c517f481727b8b313e19a84c5bc573e7) to the `stat` message:

- `platform`
- `contact_email`
- `description`

I can implement these fields myself as soon as I have time. If anyone else wants to do this, please add a comment.

**Comment by brocaar** [comment]
I've added a `CustomData` field, which is a `map[string]interface{}` to the stats struct (https://github.com/brocaar/loraserver/commit/25876c69ca395361440e98b1f71c6ce298d01dd9).
