### ISSUE TITLE
level=error msg="gateway: could not handle packet: gateway: could not base64 decode data: illegal base64 data at input byte 0" 

### ISSUE THREAD

**Issue by lf529** [brocaar/lora-gateway-bridge#80]
level=error msg="gateway: could not handle packet: gateway: could not base64 decode data: illegal base64 data at input byte 0" 
### What happened?
What's the problem?

**Comment by lf529** [comment]
?

**Comment by brocaar** [comment]
Could you let me know how to reproduce this issue?
