### ISSUE TITLE
 TX_FREQ error when a new sensor want to join lora network 

### ISSUE THREAD

**Issue by yutingWW** [brocaar/lora-gateway-bridge#81]
Hi everyone, when a new node need to be add to network

the lora server receive the join request and also accept a join accepted topic is sent, but from lora gateway bridge i found this information:

févr. 09 16:08:08 loraserv lora-gateway-bridge[649]: time=“2018-02-09T16:08:08+01:00” level=error msg=“gateway: tx ack received” error=“TX_FREQ” mac=7276ff000b030706 random_token=0

they said this problem appear when package is rejected because requested frequency is not supported by TX RF chain

Can anyone help me with this issue?
Thank you!

**Comment by brocaar** [comment]
Please use the forum for support related questions: https://forum.loraserver.io. Thanks!
