### ISSUE TITLE
ApplyConfiguration panic

### ISSUE THREAD

**Issue by gq-tang** [brocaar/lora-gateway-bridge#90]
### Out of index panic occurs when the gateway channel in loraserver is set to be greater than 8.

<pre>
if multiSFCounter >= channelCount {
					return gc, errors.New("gateway: exceeded maximum number of multi-sf channels")
				}
</pre>

**Comment by brocaar** [comment]
The error:

`errors.New("gateway: exceeded maximum number of multi-sf channels")`

is intentional as the sx1301 / sx1308 on your gateway does not support > 8 multi-spreadingfactor channels.

**Comment by gq-tang** [comment]
I see, but if the number of channels set on loraserver is >8, gateway-bridge will panic instead of returning an error.
> should be changed to >= in [source code](https://github.com/brocaar/lora-gateway-bridge/blob/master/internal/gateway/semtech/pf_config.go#L247)

**Comment by brocaar** [comment]
Ah, good catch! Would you like to make a pull-request to change this?

**Comment by brocaar** [comment]
Closing as the pull-request fixing this has been merged.
