### ISSUE TITLE
Please help me find out solution with LoRaWAN

### ISSUE THREAD

**Issue by iotproductions** [brocaar/lora-gateway-bridge#99]
Dear all,

I'm a newbie with LoRa technologies and LoRaWAN.
I'm planning to deploy a simple network using LoRaWAN. I'm going to use  RAK831  and Raspberry Pi for Gateway side. Sensor Node: I'm going to use SX1278 chip collect some sensor'data then send them to th Gateway. Inside the Gateway I will install lora-gateway-bridge to forward all incomming data from Sensor Node to my MQTT Broker.
Can you please give me some suggestions for my solution ?
Do I understand it right?
Thanks all !

**Comment by brocaar** [comment]
I'm closing this issue. It has nothing to do with a LoRa Gateway Bridge bug report or feature request.
